### ISSUE TITLE
error on migrate 

### ISSUE THREAD

**Issue by stakervali** [jazzband/django-newsletter#372]
If I enable imperavi code editor via `settings` and run a migration on a fresh, empty project, I got error

`Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "J:\Kodlar\scratch\django\newsletter_uyg\venv\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_lin
  File "J:\Kodlar\scratch\django\newsletter_uyg\venv\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_
  File "J:\Kodlar\scratch\django\newsletter_uyg  File "J:\Kodlar\scratch\django\newsletter_uyg\venv\lib\site-packages\django\core\management\
  File "J:\Kodlar\scratch\django\newsletter_uyg\venv\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "J:\Kodlar\scratch\django\newsletter_uyg\venv\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    django.setup()
  File "J:\Kodlar\scratch\django\newsletter_uyg\venv\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "J:\Kodlar\scratch\django\newsletter_uyg\venv\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "J:\Kodlar\scratch\django\newsletter_uyg\venv\lib\site-packages\django\apps\config.py", line 224, in create
    import_module(entry)
  File "C:\Users\yalcin\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'imperavisorl'
`

I have searched through all files and could not find 'imperavisorl' in any of them.

python version 3.8.8

asgiref==3.3.4
chardet==4.0.0
Django==3.2.4
django-imperavi==0.2.3
django-newsletter==0.9.1
django-tinymce==3.3.0
ldif3==3.1.1
Pillow==8.2.0
python-card-me==0.9.3
python-dateutil==2.8.1
pytz==2021.1
six==1.16.0
sorl-thumbnail==12.7.0
sqlparse==0.4.1
surlex==0.2.0
unicodecsv==0.14.1

**Comment by woodz-** [comment]
It seems you need to intall the [sorl-thumbnail](https://pypi.org/project/sorl-thumbnail/)  package.
Could it be that you messed your settings.py? `imperavisorl` is not a known Python module nor package. It seems you forgot a comma or space.
